### ISSUE TITLE
HSCT - Hematopoietic stem cell transplantation treatment option to be amended

### ISSUE THREAD

**Issue by OPTIMISE2020** [dsi-icl/optimise#1004]
Can the treatment option for HSCT be amended for this treatment only.  Essentially, this medication is calculated based on weight and blood test results and sites are unable to enter this treatment because of a few mandatory fields that does not allow them to proceed to save the form.

Please can the dose and unit fields for HSCT be made non-mandatory for this treatment only?  Is it possible to programme the dose and unit fields to accept a blank field?  Sites have some information for this treatment and are happy to leave a conscience message in the communication field.

Happy for your thoughts on this.

**Comment by sou-chon** [comment]
To allow and prohibit field to be blank depending on other fields would complicate the bussiness logic of the app and possibly introduce new bugs.

A easy fix i think of is if i add an "N/A" field in the unit - and when the treatment is displayed it will show N/A. But this would not be specific to HSCT. What do you think?

**Comment by OPTIMISE2020** [comment]
Dear Chon,

Perfect!  Sounds like the best solution to keep the database bug free.


Kind Regards,
Aleisha Miller
OPTIMISE:MS Clinical Project Manager

Division of Brain Sciences   ¦   Imperial College London   ¦   Hammersmith Hospital Campus
Room E501, 5th floor Burlington Danes Building   ¦   Du Cane Road  ¦  London ¦ W12 0NN
T: 0207 594 1357  ¦  E: aleisha.miller1@imperial.ac.uk<mailto:aleisha.miller1@imperial.ac.uk>

**Comment by OPTIMISE2020** [comment]
Perfect.  I have just tested this in the newest version of the database and it works seamlessly.  Thank you for your hard work.

**Comment by sou-chon** [comment]
292f30c81225aacb687f5e5feea90f537d77460c
