### ISSUE TITLE
Recording of every actions made by the user

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#128]
Each actions of the user should be saved in the data base.
- [x] Define all actions possible.
- [x] Create a conception of the database's table(s) needed.
- [x] Create the table(s) in the database.
- [x] Add to the server a monitoring of the actions.
- [x] Add the actions monitored to the database

**Comment by fguitton** [comment]
Refer to #151

**Comment by Radiateurs** [comment]
[Update]
The table's columns are formatted as the following
id | router | method | user | body | createdTime

**Comment by Radiateurs** [comment]
Closed in commit 42a43b8c5afacea7072c5232151e031f3180957c
