### ISSUE TITLE
Modification of the user informations

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#132]
A user can modify its own information.
- [x] Change password w/ confirmation
- [x] Deletion of the data (i.e. setting the field "deleted" to true and not erase the information of the user)
- [ ] Erasure of the data (i.e. Erase every information about the user)

**Comment by fguitton** [comment]
We must make sure there is a way to handle consent withdrawal

**Comment by fguitton** [comment]
@Radiateurs How relevant is erasure of users ? I thought we had dismissed this already ?
