### ISSUE TITLE
Patient main modification

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#140]
A user can modify all the information related to a patient.
- [x] Profile #135 
- [x] Visit #136 
- [x] Clinical Event #137 
- [x] Tests #138 
- [x] Treatment #139 

The (super)admin user should be able to erase all patient data if patient consent is withdrawn.

**Comment by epissari** [comment]
Points to consider:

1. Multiple types of consent? In the current version, the user is asked whether the patient gives consent for their data to be shared.
2. What (patient) information, if any, is retained after a patient is erased? (ref point 1)
3. Is consent information stored? In the current version, if patient gives consent, this info is stored as the date the user created the patient.

**Comment by fguitton** [comment]
@epissari In the context of this application we are expecting participants to be given a single privacy notice. The a participant calls upon their right to be forgotten we must store at least their name or NHS number, ideally in some sort of non-reversible hashed form (#161).
