### ISSUE TITLE
Dummy patients not being deleted from central database

### ISSUE THREAD

**Issue by ewadding** [dsi-icl/optimise#1436]
We have become aware of several patients that either (i) have been deleted by site staff, but who remain on the central database with no indication that they have been deleted, or (ii) the site staff are unable to delete.

This became apparent when we queried some of the data on these patients, as it appeared unusual, but the site staff could not find the Optimise IDs on their laptops. On further investigation it appeared that these were "dummy" patients that were created to test/demonstrate the local site laptops and which had already been deleted locally.  However, they remain on the central database.  In other cases the site staff could find the dummy patients but reported that the system would not allow them to delete them.

Please can you investigate, and find a way to either delete these patients from the central DB, or flag them so they can be excluded from study analyses.

The affected patient records that I am aware of are attached, however we have reason to believe (based on reported recruitment numbers) that this list is incomplete and the problem may be more widespread.  Is it possible to identify any other affected records?  If not, we may need to obtain a full list of genuine patient IDs from the sites and reconcile these with what is on the central DB.

[dummyPatients.csv](https://github.com/dsi-icl/optimise/files/7610788/dummyPatients.csv)

**Comment by fguitton** [comment]
Dear @ewadding, just to add some context first, the system is designed to keep trace of every record, including the deleted ones. Similarly to every other data, this is done through the `deleted` field which typically would contain `[number@number]`. The the first patient in your attached file (`34e50de6-e974-4ff5-b4a9-43cb133f68ad`) you can see to records, both of which have the `deleted` field set. It suggests that the patient data were edited once and it was later deleted. One is set to `9@1604394559657`, this means user `9` deleted this patient at timestamp `1604394559657`. It is the good strategy to rely on this field to filter your queries.

This said, considering the list you sent, there is definitely room for a bug here, and I will let @adityadhawan22 pick this up and keep you in the loop.

**Comment by ewadding** [comment]
Thanks Florian, I'm aware of the deleted field and all my analyses usually filter out any patients where it's non-blank.  It looks like the site may have eventually managed to delete that one after I originally queried the data, and my list needed updating.    Nevertheless I am pretty sure there is a real issue here for the majority of the listed records.
