### ISSUE TITLE
Add Treatment to patient 

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#144]
A user can add a new treatment to the patient's information
- [x] Treatments
   - [x] Category
   - [x] Name
   - [x] Dose
   - [x] Unit
   - [x] Form
   - [x] Frequency
   - [x] Start Date
   - [x] End Date
- [x] Drug Interruptions
   - [x] Dates
   - [x] MeDRA codings
- [x] Drug discontinuation
   - [x] Dates
   - [x] MeDRA codings

**Comment by epissari** [comment]
The user should be able to add

- [ ] Treatment category, name, dose, unit, form and frequency

- [ ] Treatment start, end, discontinuation and interruption dates

- [ ] Reason for interruption and/or discontinuation and MedDRA coding

**Comment by epissari** [comment]
Points to consider

1. Are multiple entries with the same treatment name and/or treatment start date for a particular patient allowed?
2. Are treatment names other than those provided in the treatment list allowed? Free form input?
3. Does the list of treatment names change based on the treatment category that the user selects?
4. Perform checks on the dates e.g. the last interruption restart date should be before the discontinuation date (this is related to point 1 above).
