### ISSUE TITLE
Add Patient Profil

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#149]
A user can add all the information related to the new user's profile.
- [x] Demographic
  - [x] Date of birth
  - [x] Gender
  - [x] Dominant hand side
  - [x] Ethnicity
  - [x] Country of origin
  - [x] Smoking history (age > 18)
  - [x] Alcohol history (age > 18)
- [x] Medical History
  - [x] Medical condition, onset and outcome
  - [x] Immunizations (age <= 18)
  - [x] Pregnancy details for female patients
- [x] Family Medical History
  - [x] Relationship and condition
- [ ] Primary Diagnosis
  - [ ] Symptoms details
  - [ ] Diagnosis details
  - [ ] Basis of diagnosis for MS diagnoses

**Comment by epissari** [comment]
The user should be able to add the following Demographic data:

- [ ] Date of birth

- [ ] Gender

- [ ] Dominant hand side

- [ ] Ethnicity

- [ ] Country of origin

- [ ] Smoking history for patients > 18 years

- [ ] Alcohol consumption for patients > 18 years

The user should be able to add the following Medical History data:

- [ ] Medical conditions, onset and outcome

- [ ] Immunisations for patients <= 18 years

- [ ] Pregnancy details for female patients

The user should be able to add the following Family Medical History data:

- [ ] Relationship and condition

The user should be able to add the following Primary Diagnosis data:

- [ ] First symptoms details

- [ ] Diagnosis details

- [ ] Basis of diagnosis for Multiple Sclerosis diagnoses

**Comment by fguitton** [comment]
@Radiateurs @epissari Any progress on this ?
