### ISSUE TITLE
Timeline is compressed and unclear (dates overlap, no shrinking)

### ISSUE THREAD

**Issue by epissari** [dsi-icl/optimise#15]
Feedback from Oxford: "The MS research team do not appreciate the graphics, particularly the circles on the timeline. There is no capacity to hover over the icons for clinic dates or relapses and have information about the episodes such as actual dates, steroids, or even the type of clinic such as DMT clinic, nurse clinic, and relapse clinic...The primary diagnosis does not appear on the timeline."

**Comment by fguitton** [comment]
Here again, it would be great to obtain a screenshot exhibiting the wrongful behaviour so we get a clearer idea as to what to correct.
