### ISSUE TITLE
/api/patientProfile/:patientId renaming to /api/patients/:patientId

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#152]
By remodeling the structure of the back-end, I created routes to have a better organisation.
Each section has a router that handle its requests. 

To handle the patient information (i.e. /api/aptients/) a router has been created. The request /api/patientProfile/:patientId/ sends  the information related to a patient. It would be smarter to rename the profile request to /api/patients/:patientId/ so this request can be handled by the router charged of the patient related requests.

**Comment by sou-c** [comment]
wouldn't it be confusing to people that /patients?id=xxx and /patients/:patientId do different things? can you not direct both endpoints to the same router?
