### ISSUE TITLE
Add export functionatlity

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise#153]
The application must have a bare minimum export function to allow users to grab the data in a JSON or tabular format (flattening model to be considered carefully)

- [x] Export entire dataset
- [x] Export after search
- [x] Export data about given patient (#GDPR)
- [ ] Export filter (user selects domains/variables to include in export)

**Comment by epissari** [comment]
I understand the exported data set in all of the 3 cases listed should follow the CDISC variable naming conventions and the CDISC SDTM format in general?

**Comment by fguitton** [comment]
@epissari The data export as such can exist in a single format, but should probably exist in 2 format, one machine readable (I don't mean binary, but something easily usable programatically)/on human readable (like a verbose report; i.e. GDPR). We obviously have to define what these format will look like. Obviously they should be constructed around CDISC terminology, that's the whole point after all.

**Comment by fguitton** [comment]
@epissari is that done ?

**Comment by fguitton** [comment]
@epissari How are we on this ?

**Comment by epissari** [comment]
Available in v1.9.30 (branch `master` commit dsi-icl/optimise-core@d578ca722af08259c9d65b3e9ea1c71b39caad8c)
