### ISSUE TITLE
Hard coded data in database schema

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#157]
We must find a way to get rid off the hard coded data in the database. 
For example in the patient_demographic_data table in the fields gender, alcohol_usage or smoking_history use hard coded data defining the value they will take. 
We must not deliver this but research a little to fine any better way to do it.

I was thinking about enumerations in the database for example or something smarter than hard coded data.

**Comment by sou-c** [comment]
due to using sqlite theres no enum type. right now for things that are categorical i put in the field table their possible values and have the server check if the input from user is valid

**Comment by Radiateurs** [comment]
Ok, I'll look in sqlite if there's any other way to do that in a more protected way.

**Comment by sou-c** [comment]
cheers
