### ISSUE TITLE
Deletion of user by username

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#159]
The request /api/users/ in DELETE  methods has to delete a certain username.
The issue here is that it use the username to match and delete the user in the database. 
Even if the creation of a user check if the username is already used, it might be better to use the id in the database.

**Comment by sou-c** [comment]
when i wrote this i didn't know if it's okay to send the user id to the user directly. i still don't know. but if it's fine then it doesn't matter which as long as it locates the user in the database
