### ISSUE TITLE
Treatment list might be incomplete

### ISSUE THREAD

**Issue by epissari** [dsi-icl/optimise#16]
Current treatment list (treatment name and treatment category):

    - name: 'Alemtuzumab (Lemtrada)', cat: 'Disease Modifying'
    - name: 'Avonex (Interferon beta-1a)', cat: 'Disease Modifying'
    - name: 'Azathioprine', cat: 'Disease Modifying'
    - name: 'Betaferon (Interferon beta-1b)', cat: 'Disease Modifying'
    - name: 'Cladribine (Mavenclad)', cat:'Disease Modifying'
    - name: 'Cyclophosphamide', cat: 'Disease Modifying'
    - name: 'Daclizumab (Zinbryta)', cat:'Disease Modifying'
    - name: 'Dimethyl fumarate (Tecfidera)', cat:'Disease Modifying'
    - name: 'Extavia (beta interferon-1b)', cat: 'Disease Modifying'
    - name: 'Fingolimod (Gilenya)', cat:'Disease Modifying'
    - name: 'Glatiramer acetate (Copaxone)', cat: 'Disease Modifying'
    - name: 'Methotrexate', cat: 'Disease Modifying'
    - name: 'Mitoxantrone', cat: 'Disease Modifying'
    - name: 'Natalizumab (Tysabri)', cat: 'Disease Modifying'
    - name: 'Plegridy (peginterferon beta-1a)', cat: 'Disease Modifying'
    - name: 'Rebif (beta interferon-1a)', cat: 'Disease Modifying'
    - name: 'Rituximab', cat: 'Disease Modifying'
    - name: 'Teriflunomide (Aubagio)', cat:'Disease Modifying'
    - name: '4-aminopyridine', cat: 'Symptomatic'
    - name: 'Corticosteroids', cat: 'Symptomatic'
    - name: 'Prednisone', cat: 'Symptomatic'
    - name: 'Amantadine', cat: 'Symptomatic'
    - name: 'Baclofen', cat: 'Symptomatic'
    - name: 'IV Methyl-prednisolone', cat: 'Symptomatic'
    - name: 'IVIG', cat: 'Symptomatic'
    - name: 'Plasma Exchange', cat: 'Symptomatic'
    - name: 'Mycophenolic Acid', cat: 'Symptomatic'
    - name: 'Neuropsych. Training', cat: 'Others'
    - name: 'Physiotherapy', cat: 'Others'
    - name: 'Cognitive Therapy', cat: 'Others'

Is the treatment list complete and accurate?

**Comment by fguitton** [comment]
Meeting with Aleisha Miller today revived this conversation

**Comment by fguitton** [comment]
Fixed in 3b29370227ed713faaa16d67c24c4887639ffc43
