### ISSUE TITLE
DELETE method to delete patient to PATCH method

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#160]
The HTTP method used to delete a certain patient is using the DELETE method.
By deletion here, we are talking about setting the field "deleted" of the patient in the databse to the actual time.
Since this doesn't reflect the true nature of the method DELETE and since we need to Erase the data of the patient through the DELETE method in the future for the GDPR compliance, it would be better to use the PATCH HTTP method for setting the deleted field.

**Comment by sou-c** [comment]
i feel like this point is up for debate. especially biologists and bioinformaticians, which are not familiar with computer but need to write some small program / pipelines, would expect a more intuitive outward behaviour. to them the internal logic or behaviour of the programme doesn't matter. they don't care whether the record is deleted or not in the database as long as the outward behaviour is (1) the record appears to them as deleted and (2) they can recover the data if really needed.

**Comment by fguitton** [comment]
This is a tricky topic. Obviously technically there is justification for using PATCH, but I understand the semantic mean that we should present to API users, which makes @sou-c point very relevant. Who are really the projected users of the API ? That is not gonna be the clinicans or doctors. I will enquiry about this.

**Comment by epissari** [comment]
@fguitton I think the teams in Belgium and Poland would use the API. I will confirm.

**Comment by fguitton** [comment]
@epissari When we talk about projected users here, we are not talking about specific stakeholder, we are talking about the profile of people: bioinformaticians, developers, …

**Comment by epissari** [comment]
@fguitton Yes, this is clear. @sou-c explained- we discussed this. The teams I mentioned include developers. I will enquire.

**Comment by Radiateurs** [comment]
Any news ?

**Comment by epissari** [comment]
As I mentioned, software developers from two of the teams requested the API in the past but we cannot tell if this is still the case. Maybe it would be best to go with your initial suggestion @Radiateurs as there is no particular target at the moment?

**Comment by Radiateurs** [comment]
It is only a matter of doing the smartest thing.
After thinking about it, we can keep the DELETE method for both case but add a parameter in the body that will request an erasure and without this parameter a simple deletion.
1 request, 2 actions
