### ISSUE TITLE
Adding a new drug: Ofatumumab (Kesimpta)

### ISSUE THREAD

**Issue by OPTIMISE2020** [dsi-icl/optimise#1650]
Dear Team,

Can Ofatumumab (Kesimpta) be added to the existing drug list on OPTIMISE please?  This is a new DMT.

Best wishes
Aleisha

**Comment by fguitton** [comment]
Dear @OPTIMISE2020,
This was already requested in #1534 and addressed in the subsequent contribution #1546.
I shall prepare a new release of the software for this to make it to the site
