### ISSUE TITLE
Patient data can be entered (but not stored) if ID entered in New Patient window already exists

### ISSUE THREAD

**Issue by epissari** [dsi-icl/optimise#25]

**Comment by epissari** [comment]
Proposed fix in commit 59846a7eca20114f2e6ef07ba2324c54928241e7.

**Comment by fguitton** [comment]
@epissari How is the progress on that ?

**Comment by epissari** [comment]
Proposed fix in candidate branch `fix-issue-25` commit 4089eecd7295a59ce445ea35eebbb938ca7f216c.
