### ISSUE TITLE
'View all reminders' does not show currently set reminders

### ISSUE THREAD

**Issue by epissari** [dsi-icl/optimise#27]
Clicking 'View all reminders' shows no reminders even though there are clearly reminders set for at least one patient.

![allreminders](https://user-images.githubusercontent.com/29205869/38674133-4dd7cd76-3e4b-11e8-9d7a-24bd0e1b2231.png)

**Comment by fguitton** [comment]
What does that even mean ? Could you describe the problem ? Possibly with visual evidence.

**Comment by epissari** [comment]
'View all reminders' will currently only show Blood/Serological/MRI reminders when there have already been created respective entries for tests recorded in the past in section 'Tests'. Question: Would it be useful to allow the user to set a reminder for a test with no 'matching' entry in Tests, for example, set an MRI reminder when there are no MRIs recorded in Tests?

**Comment by epissari** [comment]
Fix proposed in commit 0f1abc79dd610c5514aae1c2ad558a1a191d4f78.

![rem](https://user-images.githubusercontent.com/29205869/39360827-aae117fc-4a17-11e8-9597-da8f16bd3705.png)
