### ISSUE TITLE
User can accidentally delete / easily overwrite data without being prompted for validation

### ISSUE THREAD

**Issue by epissari** [dsi-icl/optimise#30]

**Comment by epissari** [comment]
Response from Paul Matthews:

> It is important that SOMEONE can delete all of a patient record (e.g., if a patient removes consent for data to be held).  This must be carefully controlled to avoid inadvertent data loss. Can an entry be corrected at a later time if it was inaccurately entered?

**Comment by epissari** [comment]
Related to issues #10 and #28.

Need to specify the group of users who can delete/update/recover data. Some data can be updated easily (for example, symptoms are set by button clicks) while some other require more effort. In order to edit a particular Medical History (Profile) entry, for example, the user needs to delete that entry.

**Comment by fguitton** [comment]
@epissari, I am not sure I understand what you are describing in you previous post. Are you talking about the current behaviour or are you asking a question ? Please clarify.
