### ISSUE TITLE
Fix Reminders- if On clicked before type and time are set, user cannot add/delete/edit any data in this section

### ISSUE THREAD

**Issue by epissari** [dsi-icl/optimise#32]

**Comment by fguitton** [comment]
Could you please substanciate this with a screenshot to make it clearer, I believe I understand from prior discussions but it would make it clearer what you mean.

**Comment by epissari** [comment]
If the user clicks 'On' first and then selects type and time (here Serological and 1/year, respectively), it is not possible to edit or delete that particular reminder or add more reminders.

![reminders](https://user-images.githubusercontent.com/29205869/38673492-688cfee0-3e49-11e8-8751-6d5c1430563e.png)

**Comment by epissari** [comment]
Proposed fix in commit 08c1d678c4900dc0f2d917504a88b3712cef3f4d
