### ISSUE TITLE
Mapping file export for patient at the site

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise#378]
It has come to my attention that on top of providing patient search from Optimise ID, we will want to also enable the export of a bridging file from Optimise ID to Patient ID by that administrators directly at the site.

**Comment by sou-chon** [comment]
2f85f23a55de54b4d4cc590a5a51e1ee2d7e3dba

**Comment by fguitton** [comment]
This is not solves. We will export the UUID in all export files and offer an admin option for exporting mappings.
