### ISSUE TITLE
'Cover' misaligned in some browser

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise#62]
![screen shot 2018-04-20 at 16 18 30](https://user-images.githubusercontent.com/35537528/39059483-89fc6890-44b6-11e8-97f4-58e60dc3949a.png)

it causes some buttons underneath to be exposed

**Comment by sou-c** [comment]
![screen shot 2018-04-20 at 16 35 38](https://user-images.githubusercontent.com/35537528/39060334-fb1d0adc-44b8-11e8-9ce9-4c3c8ff60d75.png)

**Comment by epissari** [comment]
Fixed in candidate branch `fixes-oxford-april` commit 62d14b5db048ca3da57d74f84168d46487ff8756 :)
