### ISSUE TITLE
Accordions are not always properly disabled when no visit/event/test/... is selected

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise#64]
in 'visit', when no visit is created/selected, sign and symptoms sections can't toggle. but the others can (but user can't enter any data). when a visit is selected, all can be toggled

**Comment by sou-c** [comment]
same thing for other tabs

**Comment by fguitton** [comment]
There is stupid getDisabledFields function sprinkled everywhere which seem to be causing the problem

**Comment by fguitton** [comment]
Fix proposed in commit 77c8b6c
