### ISSUE TITLE
UI left selection panel should update appropriately upon item creation

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise#67]
When creating a new visit / event / treatment / ... the left panel offers a datepicker to create a new occurrence. Upon successfully creating the occurrence, the UI stays stuck in this configuration :
![image](https://user-images.githubusercontent.com/2495155/39111806-b984e78c-46d6-11e8-9657-976664b25bc6.png)

The expected immediate outcome should be : 
![image](https://user-images.githubusercontent.com/2495155/39111850-d82ea2ae-46d6-11e8-8163-07d06e6ffd77.png)

We should be able to clearly see the selected occurrence and see the datepicker disappear

_P.S. There is an ungodly scroll bar that needs addressing at the same time._

**Comment by fguitton** [comment]
Part of this is now fixed in commit 5812816a. There are inconsistencies in behaviour between different section.

**Comment by fguitton** [comment]
There is a problem where treatement name used to display : 
![image](https://user-images.githubusercontent.com/2495155/39316008-0833bfe8-4970-11e8-9801-e996f6b89efb.png)
And does not anymore : 
![image](https://user-images.githubusercontent.com/2495155/39316037-177312ec-4970-11e8-88df-37995ff4aa15.png)
As such, I don't beleive it is an issue, but we will have to consult on this.

**Comment by epissari** [comment]
This may also apply to Relapses where the list included date and severity?

**Comment by fguitton** [comment]
This issue is considered fixed but there are multiple side effects with the current system that will need to be qualified in further issues. Their resolution is likely to be complex.
