### ISSUE TITLE
Need no change/stable and resolving/resolved lesion options in MRI

### ISSUE THREAD

**Issue by elen-oui** [dsi-icl/optimise#7]
Further clarification as to how this feature should be implemented is required. Current options for Brain and Spine Morphology are shown in the screenshots below. Would the new feature be available as an option? How will we indicate the comparison ('no change' compared to which MRI)?

![mribrain](https://user-images.githubusercontent.com/29205869/38384152-4c5953ba-3906-11e8-808e-4132350fbce0.png)
![mrispine](https://user-images.githubusercontent.com/29205869/38384159-4f433244-3906-11e8-9f2b-876dc0b4228e.png)

**Comment by epissari** [comment]
Response from Paul Matthews for no change/stable lesion options:

> Need Box (lower left) saying:  “Change from last scan”.  Noting as:
“No change”
“Less disease activity”
“Disease progression”

Response from Paul Matthews for resolving/resolved lesion options:

> Ignore for now

**Comment by epissari** [comment]
How should we implement "Change from last scan" options? Are there any relevant CDISC standards? An example of how MRI scan (Morphology section) data is currently stored in OptimiseMS is given below.

    "STUDYID" : "OPTIMISE", 
    "DOMAIN" : "MO", 
    "USUBJID" : "OPT-DM-02-10005", 
    "SPDEVID" : "", 
    "MOSEQ" : NumberLong(0), 
    "MOLNKID" : "", 
    "MOREFID" : "", 
    "MOTESTCD" : "", 
    "MOTEST" : "T1 Lesion Count Summary", 
    "MOORRES" : "Positive", 
    "MOORRESU" : "", 
    "MOSTRESC" : "", 
    "MOSTRESN" : "", 
    "MOSTRESU" : "", 
    "MOLOC" : "Brain", 
    "MOSLOC" : "", 
    "MOLAT" : "", 
    "MOMETHOD" : "", 
    "MOANMETH" : "", 
    "MODTC" : "2018-03-01T00:00:00.000Z", 
    "displayLabel" : "T1 Lesion Count Summary", 
    "displayDate" : "Thu Mar 01 2018"
