### ISSUE TITLE
Add a new feature to the MRI test reults forms

### ISSUE THREAD

**Issue by OPTIMISE2020** [dsi-icl/optimise#962]
Some sites have reported that their MRI reports do not report the T1 and T2 hypointense lesions.  Instead the reports will just say "Stable - No new lesions reported".    Therefore, could a new panel be added stating for example: Stable - No new lesions reported at the end of the current MRI form after "Brain atrophy".

**Comment by sou-chon** [comment]
Isn't it the same as filling in 0 for both T1 new lesions and T2 new lesions?
