### ISSUE TITLE
Create a way for sites to obtain non-anonymised data locally in csv files as the custodians in 

### ISSUE THREAD

**Issue by OPTIMISE2020** [dsi-icl/optimise#993]
Sites would like to download the data entered onto the laptops that isn't anonymised.  At present all data except PII is downloaded in the csv file.   Is there a way that we could generate a secure feature within the database that if a site requests full access to their data that we could grant access via a security key (maybe?!?) they enter into OPTIMISE to release the full data download into a CSV file.  We thought that if such a request was placed that it would need to be authorised first by the CI, PI, DSI and sponsor.  
Happy for us to discuss this via teams to firm up the details.

**Comment by sou-chon** [comment]
I can do this - let's find a time to discuss further in teams. As this is more involved it might not be in time for release together with the front-page release.

**Comment by OPTIMISE2020** [comment]
Hello Chon,

I have availability this coming Wednesday?  What time works for you?

Kind Regards,
Aleisha Miller
OPTIMISE:MS Clinical Project Manager

Division of Brain Sciences   ¦   Imperial College London   ¦   Hammersmith Hospital Campus
Room E501, 5th floor Burlington Danes Building   ¦   Du Cane Road  ¦  London ¦ W12 0NN
T: 0207 594 1357  ¦  E: aleisha.miller1@imperial.ac.uk<mailto:aleisha.miller1@imperial.ac.uk>
